services:
  db:
    image: postgres:16-alpine
    container_name: birthday-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-birthday_notification}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-birthday_notification}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birthday-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/birthday_notification
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-123}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      WHATSAPP_GROUP_ID: ${WHATSAPP_GROUP_ID:-120363407565980215@g.us}
      GREEN_API_INSTANCE_ID: ${GREEN_API_INSTANCE_ID:-7107594392}
      GREEN_API_TOKEN: ${GREEN_API_TOKEN:-b54c73d547204c48943f17c4e02aecf5804126494021456898}
      # Optional external config:
      GEMINI_API_KEY: ${GEMINI_API_KEY:-AIzaSyAt5sgyqXZxChK8ARpdHebUgNWtMZJ-AJg}
      # MAIL_HOST: ${MAIL_HOST}
      # MAIL_PORT: ${MAIL_PORT}
      # MAIL_USERNAME: ${MAIL_USERNAME}
      # MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "8081:8080"
